import Head from "next/head";
import styles from "../styles/Home.module.css";
import { Image, Transformation, CloudinaryContext } from "cloudinary-react";

import images from "../data/images.json";

export default function Gallery() {

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <ul className={styles.images}>
          {images.map((image) => {
            return (
              <li key={image.id}>
                <div className={styles.images}>
                  <CloudinaryContext cloudName="demo" >
                    <Image
                      publicId="cld-sample"
                      alt="profile"
                      className={styles.imagesBox}
                    >
                      <Transformation overlay="lighthouse" />
                      <Transformation
                        effect="style_transfer:preserve_color:30"
                        flags="layer_apply"
                      />
                    </Image>
                  </CloudinaryContext>
                </div>
              </li>
            );
          })}
        </ul>
      </main>
    </div>
  );
}
